pipeline{
    agent { label "one" }
    stages{
        
        stage("Code"){
            steps{
            echo "This is cloning the code"
            git url: "https://github.com/LondheShubham153/django-notes-app.git" , branch:"main"
            echo "Code Cloning successful"
            }
        }
        stage("Build") {
            steps{
            echo "This is building the code"
            sh "docker build -t notes-app:latest ."
        }
        }
        stage("Push to DockerHub") {
            steps{
            echo " This is pushing the image to Docker Hub"
            withCredentials([usernamePassword(
            credentialsId: "dockerHubCred",
            passwordVariable: "dockerHubPass",
            usernameVariable: "dockerHubUser")]){
            sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass} "
            sh "docker image tag notes-app:latest ${env.dockerHubUser}/notes-app:latest"
            sh "docker push ${env.dockerHubUser}/notes-app:latest"

            }
        }
            }
        stage("Deploy") {
            steps{
            echo "This is deploying the code"
            sh "docker run -d -p 8000:8000 notes-app:latest"
        }
        }
        }
    }

